In [7]:
import numpy as np

In [8]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
# Arithematic operations 
# all operations are element by element
print(arr+2)
print(arr-5)
print(arr+arr)
print(arr*arr)
print(arr-arr)


[ 2  3  4  5  6  7  8  9 10 11]
[-5 -4 -3 -2 -1  0  1  2  3  4]
[ 0  2  4  6  8 10 12 14 16 18]
[ 0  1  4  9 16 25 36 49 64 81]
[0 0 0 0 0 0 0 0 0 0]


In [10]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
# handles division by zero by giving warning not direct error 
arr/arr

C:\Users\ASUS\AppData\Local\Temp\ipykernel_12388\2367641627.py:2: RuntimeWarning: invalid value encountered in divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [12]:
1/0

ZeroDivisionError: division by zero

In [13]:
1/arr

C:\Users\ASUS\AppData\Local\Temp\ipykernel_12388\255282349.py:1: RuntimeWarning: divide by zero encountered in divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [15]:
print(np.sqrt(arr))
print()
print(np.sin(arr))
print()
print(np.log(arr))

[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]

[ 0.          0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427
 -0.2794155   0.6569866   0.98935825  0.41211849]

[      -inf 0.         0.69314718 1.09861229 1.38629436 1.60943791
 1.79175947 1.94591015 2.07944154 2.19722458]


C:\Users\ASUS\AppData\Local\Temp\ipykernel_12388\184357395.py:5: RuntimeWarning: divide by zero encountered in log
  print(np.log(arr))


In [16]:
print(arr.sum())
print(arr.max())
print(arr.mean())
print(arr.var())
print(arr.std())

45
9
4.5
8.25
2.8722813232690143


In [18]:
arr_2d = np.arange(0,25).reshape(5,5)
arr_2d


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [19]:
print(arr_2d.sum())
print(arr_2d.sum(axis = 0)) # perform sum across the rows --> sum of columnns as each element
print(arr_2d.sum(axis = 1)) # perform sum across the colums --> sum of rows as each element


300
[50 55 60 65 70]
[ 10  35  60  85 110]
