In [1]:
import numpy as np

In [3]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
print(arr[8])
print(arr[1:5])
print(arr[0:5])
print(arr[:5])
print(arr[5:])
print(arr[1:5:1])
print(arr[1:5:2])

8
[1 2 3 4]
[0 1 2 3 4]
[0 1 2 3 4]
[ 5  6  7  8  9 10]
[1 2 3 4]
[1 3]


## Broadcasting 

In [7]:
arr[:4] = 100
arr

array([100, 100, 100, 100,   4,   5,   6,   7,   8,   9,  10])

In [8]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
slice_of_arr = arr[0:4]
print(slice_of_arr)
slice_of_arr[:]= 99   # this array elements points to the location of elements of arr
print(slice_of_arr)
print(arr)

[99 99 99 99]
[99 99 99 99]
[99 99 99 99  4  5  6  7  8  9 10]


In [14]:
# How to not affect the original array and copy the contents of array
arr_copy = arr.copy()
print(arr_copy)
print(arr)
arr_copy[:] = 100
print(arr_copy)
print(arr) # original copy do not change

[99 99 99 99  4  5  6  7  8  9 10]
[99 99 99 99  4  5  6  7  8  9 10]
[100 100 100 100 100 100 100 100 100 100 100]
[99 99 99 99  4  5  6  7  8  9 10]


## Indexing in 2D arrays


In [34]:
array_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(array_2d)
print(array_2d.shape)
print(array_2d[0])
print(array_2d[2][2])
#  OR
print(array_2d[2,2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
[1 2 3]
9
9


In [37]:
# 2D array slicing
print(array_2d[:2])
print()
print(array_2d[:2,1:])
print()
print(array_2d[:2][1:])

[[1 2 3]
 [4 5 6]]

[[2 3]
 [5 6]]

[[4 5 6]]


## Conditional Selection

In [38]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [39]:
arr>4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [40]:
bool_arr = arr>4
print(bool_arr)
arr[bool_arr]

[False False False False  True  True  True  True  True  True]


array([ 5,  6,  7,  8,  9, 10])

In [41]:
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])

In [43]:
len(arr[arr>4])

6