## Numpy Arrays

In [4]:
import numpy as np

In [5]:
mylist = [1,2,3]
type(mylist)

list

In [6]:
myarr = np.array(mylist)
type(myarr)

numpy.ndarray

In [7]:
my_matrix=[[1,2,3],[4,5,6],[7,8,9]]
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
np.arange(0,100,20) # start,end,stepsize


array([ 0, 20, 40, 60, 80])

In [9]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [10]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
np.zeros((2,5)) # rows,columns

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [18]:
print(np.ones((5,5)))
np.ones(5)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


array([1., 1., 1., 1., 1.])

In [14]:
np.linspace(0,10,11) # start ,end,how many numbers to be generated 

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [15]:
np.eye(5) # identity matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [19]:
np.random.rand(5,2)  # use uniform distribution - any number between [0,1) is picked
# and probability of any number to be picked is uniform

array([[0.66390657, 0.40747379],
       [0.94100402, 0.76517511],
       [0.32634046, 0.26187033],
       [0.61123832, 0.64760688],
       [0.71502357, 0.92369959]])

In [21]:
np.random.randn(5,2) # use standard normal distribution - number close to zero have higher probability to be picked


array([[ 0.67235601,  0.45899275],
       [ 0.16411806, -2.30275032],
       [ 0.33414273, -0.5912265 ],
       [-0.48446427, -0.59902338],
       [-1.54029635,  0.40166492]])

In [28]:
np.random.randint(0,100,(2,10)) # Random integer between start and end in the form of numpy array

array([[25, 76, 22, 36, 15, 33, 97, 62, 94, 44],
       [76, 74, 89,  0, 32, 90, 49, 36, 31, 38]])

In [41]:
np.random.seed(11)
np.random.rand(4,2) # this two line will generate the same values again and again 

array([[0.18026969, 0.01947524],
       [0.46321853, 0.72493393],
       [0.4202036 , 0.4854271 ],
       [0.01278081, 0.48737161]])

In [44]:
arr = np.arange(0,25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [47]:
arr.reshape(5,5) 
# arr.reshape(5,4) --> error as cannot fit 25 items 5X4 = 20 spaces 

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [48]:
ranarr = np.random.randint(0,101,10)
ranarr

array([32, 45,  4, 34, 12,  1, 74, 37, 84, 81])

In [52]:
print(ranarr.min())
print(ranarr.max())
print(ranarr.argmax())  # index location of max value
print(ranarr.argmin())  # index location of min value
ranarr.dtype




1
84
8
5


dtype('int32')

In [53]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [55]:
arr.shape # (25,) --> one D vector 

(25,)

In [70]:
arr1 = arr.reshape(25,1)

In [71]:
arr1.shape

(25, 1)

In [72]:
myarray = np.linspace(0,10,101)
myarray

array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ,
        1.1,  1.2,  1.3,  1.4,  1.5,  1.6,  1.7,  1.8,  1.9,  2. ,  2.1,
        2.2,  2.3,  2.4,  2.5,  2.6,  2.7,  2.8,  2.9,  3. ,  3.1,  3.2,
        3.3,  3.4,  3.5,  3.6,  3.7,  3.8,  3.9,  4. ,  4.1,  4.2,  4.3,
        4.4,  4.5,  4.6,  4.7,  4.8,  4.9,  5. ,  5.1,  5.2,  5.3,  5.4,
        5.5,  5.6,  5.7,  5.8,  5.9,  6. ,  6.1,  6.2,  6.3,  6.4,  6.5,
        6.6,  6.7,  6.8,  6.9,  7. ,  7.1,  7.2,  7.3,  7.4,  7.5,  7.6,
        7.7,  7.8,  7.9,  8. ,  8.1,  8.2,  8.3,  8.4,  8.5,  8.6,  8.7,
        8.8,  8.9,  9. ,  9.1,  9.2,  9.3,  9.4,  9.5,  9.6,  9.7,  9.8,
        9.9, 10. ])